name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci

    # Install Vue CLI
    - name: Install Vue CLI
      run: npm install -g @vue/cli

    # Run before-build script
    - name: Run before-build script
      run: node -r esm scripts/before-build.js

    # Build the Vue.js project
    - name: Build Vue.js project
      run: npm run build

    # Install vsce
    - name: Install vsce
      run: npm install -g vsce

    # Package the VSCode extension
    - name: Package VSCode extension
      run: vsce package

    # Run after-build script
    - name: Run after-build script
      run: node -r esm scripts/after-build.js

    # Run tests
    - run: npm test
